<?php
// module/JitPoll/view/jit-poll/poll/add.phtml:

$title = 'Add new poll';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<!-- Chosen Plugin -->
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin-theme/plugins/chosen/chosen.jquery.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/admin-theme/plugins/chosen/chosen.css" media="screen" />
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin-theme/js/unb/unb.validation.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin-theme/js/unb/unb.form.js"></script>
<script type="text/javascript" src="<?php echo $this->basePath(); ?>/admin-theme/js/unb/unb.ui.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#add-more-option").css('cursor','pointer');
        $("#add-more-option").click(function(){
            $("#poll-options").append('<br /><br />Option:&nbsp;<input type="text" name="poll_options[]" value="" />');
        });
    });
</script>
<div class="grid_2">
    <div class="da-panel">
        <div class="da-panel-header">
            <span class="da-panel-title">
                <img src="/admin-theme/images/icons/black/32/plus.png" alt="" />
                Add Poll
            </span>
        </div>
        <div class="da-panel-content">
            <form id="poll-form" class="da-form" action="" method="post">
                <div class="da-form-block">
                    <div class="da-form-row">
                        <label>Poll<span class="required">*</span></label>
                        <div class="da-form-item large">
                            <input type="text" name="poll_title" value="" />
                        </div>
                    </div>                   
                    <div class="da-form-row">
                        <label>Poll Options</label>                        
                        <div class="da-form-item large" id="poll-options">
                            <span class="formNote"><strong id="add-more-option">Add More</strong></span>
                            Option: &nbsp;<input type="text" name="poll_options[]" value="" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Allow user to add own answer</label>
                        <div class="da-form-item large">
                            <input type="checkbox" name="poll_user_answer_option" value="Yes" /> Yes
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Poll Publish Time<span class="required">*</span></label>
                        <div class="da-form-col-3-8">
                            Start: <input id="poll-start-datetimepicker" type="text" name="poll_start" value="" />
                            end: <input id="poll-end-datetimepicker" type="text" name="poll_end" value="" />
                        </div>
                    </div>
                    <div class="da-form-row">
                        <label>Poll Status<span class="required">*</span></label>
                        <div class="da-form-item large">
                            <input checked="checked" type="radio" name="poll_status" value="Active" /> Active &nbsp;
                            <input type="radio" name="poll_status" value="InActive" /> Active
                        </div>
                    </div>
                    
                    
                    <div class="da-form-row">
                        <input type="reset" value="Reset" class="da-button blue left" />
                        <input type="submit" value="Submit" class="da-button red" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>